from tau2.utils.utils import DATA_DIR

GAMERBIT_STORE_DATA_DIR = DATA_DIR / "tau2" / "domains" / "lopez"
GAMERBIT_STORE_DB_PATH = GAMERBIT_STORE_DATA_DIR / "db.json"
GAMERBIT_STORE_POLICY_PATH = GAMERBIT_STORE_DATA_DIR / "policy.md"
GAMERBIT_STORE_POLICY_RAG_PATH = GAMERBIT_STORE_DATA_DIR / "policy_rag.md"
GAMERBIT_STORE_TASK_SET_PATH = GAMERBIT_STORE_DATA_DIR / "tasks.json"
GAMERBIT_STORE_SPLIT_PATH = GAMERBIT_STORE_DATA_DIR / "split_tasks.json"
GAMERBIT_STORE_USER_DB_PATH = GAMERBIT_STORE_DATA_DIR / "user_db.json"
