from tau2.utils.utils import DATA_DIR

HEALTHCARE_DATA_DIR = DATA_DIR / "tau2" / "domains" / "healthcare_macalupu"
HEALTHCARE_DB_PATH = HEALTHCARE_DATA_DIR / "db.json"
HEALTHCARE_POLICY_PATH = HEALTHCARE_DATA_DIR / "policy.md"
HEALTHCARE_POLICY_SOLO_PATH = HEALTHCARE_DATA_DIR / "policy_solo.md"
HEALTHCARE_TASK_SET_PATH = HEALTHCARE_DATA_DIR / "tasks.json"
