from tau2.utils.utils import DATA_DIR

RETAIL_FARFAN_DATA_DIR = DATA_DIR / "tau2" / "domains" / "retail_farfan"
RETAIL_FARFAN_DB_PATH = RETAIL_FARFAN_DATA_DIR / "db.json"
RETAIL_FARFAN_POLICY_PATH = RETAIL_FARFAN_DATA_DIR / "policy.md"
RETAIL_FARFAN_POLICY_RAG_PATH = RETAIL_FARFAN_DATA_DIR / "policy_rag.md"
RETAIL_FARFAN_TASK_SET_PATH = RETAIL_FARFAN_DATA_DIR / "tasks.json"