from tau2.utils.utils import DATA_DIR

CONVALIDACION_DOMAIN_NAME = "ConvalidacionCLCs_Coronado"
CONVALIDACION_DATA_DIR = DATA_DIR / "tau2" / "domains" / CONVALIDACION_DOMAIN_NAME
CONVALIDACION_DB_PATH = CONVALIDACION_DATA_DIR / "db.json"
CONVALIDACION_POLICY_PATH = CONVALIDACION_DATA_DIR / "policy.md"
CONVALIDACION_TASK_SET_PATH = CONVALIDACION_DATA_DIR / "tasks.json"
CONVALIDACION_SPLIT_TASKS_PATH = CONVALIDACION_DATA_DIR / "split_tasks.json"
CONVALIDACION_TRANSFER_MESSAGE = (
    "YOU ARE BEING TRANSFERRED TO A HUMAN AGENT. PLEASE WAIT."
)

__all__ = [
    "CONVALIDACION_DATA_DIR",
    "CONVALIDACION_DB_PATH",
    "CONVALIDACION_DOMAIN_NAME",
    "CONVALIDACION_POLICY_PATH",
    "CONVALIDACION_SPLIT_TASKS_PATH",
    "CONVALIDACION_TASK_SET_PATH",
    "CONVALIDACION_TRANSFER_MESSAGE",
]
