from tau2.utils.utils import DATA_DIR

ESTACIONDESERVICIO_RIVERA_DATA_DIR = (
    DATA_DIR / "tau2" / "domains" / "estaciondeservicio_Rivera"
)
ESTACIONDESERVICIO_RIVERA_DB_PATH = ESTACIONDESERVICIO_RIVERA_DATA_DIR / "db.json"
ESTACIONDESERVICIO_RIVERA_POLICY_PATH = (
    ESTACIONDESERVICIO_RIVERA_DATA_DIR / "policy.md"
)
ESTACIONDESERVICIO_RIVERA_TASK_SET_PATH = (
    ESTACIONDESERVICIO_RIVERA_DATA_DIR / "tasks.json"
)
