from tau2.utils.utils import DATA_DIR

RESTAURANTE_JOAQUIN_CACHAY_DATA_DIR = (
    DATA_DIR / "tau2" / "domains" / "restaurante_joaquin_cachay"
)
RESTAURANTE_JOAQUIN_CACHAY_DB_PATH = (
    RESTAURANTE_JOAQUIN_CACHAY_DATA_DIR / "db.json"
)
RESTAURANTE_JOAQUIN_CACHAY_POLICY_PATH = (
    RESTAURANTE_JOAQUIN_CACHAY_DATA_DIR / "policy.md"
)
RESTAURANTE_JOAQUIN_CACHAY_POLICY_SOLO_PATH = (
    RESTAURANTE_JOAQUIN_CACHAY_DATA_DIR / "policy_solo.md"
)
RESTAURANTE_JOAQUIN_CACHAY_TASK_SET_PATH = (
    RESTAURANTE_JOAQUIN_CACHAY_DATA_DIR / "tasks.json"
)
RESTAURANTE_JOAQUIN_CACHAY_USER_DB_PATH = (
    RESTAURANTE_JOAQUIN_CACHAY_DATA_DIR / "user_db.json"
)

